/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";

export function GrassModel(props: any) {
  const { nodes, materials } = useGLTF("/models/grass.glb") as unknown as {
    nodes: { [key: string]: Mesh };
    materials: any;
  };

  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Mesh1608_Component_110_1_Component_112_1_Component_149_1_wrigle
            .geometry
        }
        material={
          nodes.Mesh1608_Component_110_1_Component_112_1_Component_149_1_wrigle
            .material
        }
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Mesh2655_Component_111_244_Component_112_244_wrigley1_Model
            .geometry
        }
        material={
          nodes.Mesh2655_Component_111_244_Component_112_244_wrigley1_Model
            .material
        }
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Mesh2887_Component_111_293_Component_112_293_wrigley1_Model
            .geometry
        }
        material={
          nodes.Mesh2887_Component_111_293_Component_112_293_wrigley1_Model
            .material
        }
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Mesh3475_Component_110_943_Component_112_472_wrigley1_Model
            .geometry
        }
        material={
          nodes.Mesh3475_Component_110_943_Component_112_472_wrigley1_Model
            .material
        }
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/grass.glb");
