/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";

export function SkyModel(props: any) {
  const { nodes, materials } = useGLTF("/models/sky.glb") as unknown as {
    nodes: { [key: string]: Mesh };
    materials: any;
  };
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Mesh9812_chair3_2_66_whiterow6_1_9_Component_280_1_Group77_alls
            .geometry
        }
        material={
          nodes.Mesh9812_chair3_2_66_whiterow6_1_9_Component_280_1_Group77_alls
            .material
        }
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Mesh10445_chair3_2_699_Component_174_27_Component_280_3_Group77
            .geometry
        }
        material={
          nodes.Mesh10445_chair3_2_699_Component_174_27_Component_280_3_Group77
            .material
        }
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Mesh15721_chair3_2_5935_whiterow6_1_140_Component_280_5_Group77
            .geometry
        }
        material={
          nodes.Mesh15721_chair3_2_5935_whiterow6_1_140_Component_280_5_Group77
            .material
        }
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/sky.glb");
